[package]
name = "cheatqol"
version = "0.1.0"
authors = ["BadAtGames26"]
edition = "2021"

[package.metadata.skyline]
titleid = "0100a6301214e000" # Fire Emblem Engage

[lib]
crate-type = ["cdylib"]

[dependencies]
cobapi = { git = "https://github.com/DivineDragonFanClub/cobapi", tag = "0.1.2" }
derive = "1.0.0"
engage-il2cpp = { git = "https://github.com/DivineDragonFanClub/engage-il2cpp", tag = "0.1.1", features = [
    "app-basicmenu",
    "app-basicmenuitem",
    "app-gameparam",
    "app-procinst",
    "app-structdata_1",
    "root-configbasicmenuitem",
    "system-collections-generic-dictionary_2",
    "system-collections-generic-list_1",
    "system-object",
] }
serde = { version = "1.0.197", features = ["derive"] }
skyline = { version = "0.6.0" }
toml = "0.8.10"
unity-nx = { git = "https://github.com/DivineDragonFanClub/unity-nx", tag = "0.1.1" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
